# Files directories
source_dir = ""
downloaded_images_folder = source_dir + "\\Images Folder"
downloaded_compressed_files_folder = source_dir + "\\Zips Folder"
downloaded_music_folder = source_dir + "\\Music Folder"
downloaded_videos_folder = source_dir + "\\Videos Folder"
downloaded_documents_folder = source_dir + "\\Documents Folder"
downloaded_design_files_folder = source_dir + "\\Design Files Folder"
downloaded_programming_files_folder = source_dir + "\\Programming Files Folder"
downloaded_font_files_folder = source_dir + "\\Font Files Folder"
downloaded_executable_files_folder = source_dir + "\\Executable Files Folder"